# nfqueue queue id
queue 3

# traffic limit in bits per second (suffixes K, M and G allowed) for parent node
limit 40M
# bucket size for parent node in bytes
burst 50K

# htb
htb yes
# htb classes, limit >= sum(classes rates)
class mark 1 rate 20m ceil 40m burst 20k
class mark 2 rate 20m ceil 40m burst 20k
#class mark 3 rate 5m  ceil 10m burst 10k
#class mark 4 rate 5m  ceil 10m burst 10k

# modules
# number of recent flows
inhibit_big_flows nrecent 10
# dump debug info every 5 seconds
#inhibit_big_flows debug 5

# entropy module
entropy nrecent 10
#entropy debug 5
entropy k 2.0
# you can override source or destination port for this module
#entropy sport 0
#entropy dport 0
